/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#fdf9f2',
        'surface-dim': '#ded9d3',
        'surface-bright': '#fdf9f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f3ed',
        'surface-container': '#f2ede7',
        'surface-container-high': '#ece8e1',
        'surface-container-highest': '#e6e2dc',
        'surface-variant': '#e6e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#434653',
        'inverse-surface': '#32302c',
        'inverse-on-surface': '#f5f0ea',
        'outline': '#737784',
        'outline-variant': '#c3c6d5',
        'surface-tint': '#1f59c1',
        'primary': '#003684',
        'on-primary': '#ffffff',
        'primary-container': '#004bb3',
        'on-primary-container': '#aec4ff',
        'inverse-primary': '#b1c5ff',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary-fixed': '#001946',
        'on-primary-fixed-variant': '#00419d',
        'secondary': '#5e5e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdb',
        'on-secondary-container': '#63635f',
        'secondary-fixed': '#e4e2dd',
        'secondary-fixed-dim': '#c8c6c2',
        'on-secondary-fixed': '#1b1c19',
        'on-secondary-fixed-variant': '#474744',
        'tertiary': '#3a3a3a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#515151',
        'on-tertiary-container': '#c5c4c3',
        'tertiary-fixed': '#e4e2e2',
        'tertiary-fixed-dim': '#c8c6c6',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fdf9f2',
        'on-background': '#1c1c18',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-padding': '8rem',
        'container-max': '1440px',
        'stack-lg': '3rem',
        'stack-md': '1.5rem',
        'stack-sm': '0.5rem',
        'gutter': '2rem',
      },
      fontFamily: {
        'headline-lg': ['Noto Serif', 'serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'display-lg': ['Noto Serif', 'serif'],
        serif: ['Noto Serif', 'serif'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
